<?php

$set = strtolower( basename(__FILE__, '.php') );

$$set = array(

  'nursing-home (nursing set)' => $set . '_f100',
  'elderly (nursing set)' => $set . '_f101',
  'elderly (nursing set)' => $set . '_f102',
  'first-aid-kit (nursing set)' => $set . '_f103',
  'shower (nursing set)' => $set . '_f104',
  'rocking-chair (nursing set)' => $set . '_f105',
  'scooter (nursing set)' => $set . '_f106',
  'hearing-aid (nursing set)' => $set . '_f107',
  'newspaper (nursing set)' => $set . '_f108',
  'medicine (nursing set)' => $set . '_f109',
  'retirement-home (nursing set)' => $set . '_f10a',
  'chess-pieces (nursing set)' => $set . '_f10b',
  'emergency-button (nursing set)' => $set . '_f10c',
  'wheelchair (nursing set)' => $set . '_f10d',
  'bed (nursing set)' => $set . '_f10e',
  'bookshelf (nursing set)' => $set . '_f10f',
  'fireplace (nursing set)' => $set . '_f110',
  'elderly (nursing set)' => $set . '_f111',
  'grandmother (nursing set)' => $set . '_f112',
  'grandmother (nursing set)' => $set . '_f113',
  'nurse (nursing set)' => $set . '_f114',
  'nurse (nursing set)' => $set . '_f115',
  'birthday-cake (nursing set)' => $set . '_f116',
  'multivitamin (nursing set)' => $set . '_f117',
  'breakfast (nursing set)' => $set . '_f118',
  'oxygen (nursing set)' => $set . '_f119',
  'crutches (nursing set)' => $set . '_f11a',
  'stair (nursing set)' => $set . '_f11b',
  'knitting (nursing set)' => $set . '_f11c',
  'electrocardiogram (nursing set)' => $set . '_f11d',
  'elevator (nursing set)' => $set . '_f11e',
  'slippers (nursing set)' => $set . '_f11f',
  'will (nursing set)' => $set . '_f120',
  'crossword (nursing set)' => $set . '_f121',
  'tennis (nursing set)' => $set . '_f122',
  'sphygmomanometer (nursing set)' => $set . '_f123',
  'domino (nursing set)' => $set . '_f124',
  'eye-test (nursing set)' => $set . '_f125',
  'emergency-call (nursing set)' => $set . '_f126',
  'walker (nursing set)' => $set . '_f127',
  'television (nursing set)' => $set . '_f128',
  'pills (nursing set)' => $set . '_f129',
  'checkers (nursing set)' => $set . '_f12a',
  'bingo (nursing set)' => $set . '_f12b',
  'diaper (nursing set)' => $set . '_f12c',
  'stretcher (nursing set)' => $set . '_f12d',
  'walking-stick (nursing set)' => $set . '_f12e',
  'toilet (nursing set)' => $set . '_f12f',
  'radio (nursing set)' => $set . '_f130',
  'sofa (nursing set)' => $set . '_f131'
);