<?php

$set = strtolower( basename(__FILE__, '.php') );

$$set = array(

  'tooth (dentistry set)' => $set . '_f100',
  'broken-tooth (dentistry set)' => $set . '_f101',
  'teeth (dentistry set)' => $set . '_f102',
  'implant (dentistry set)' => $set . '_f103',
  'teeth-1 (dentistry set)' => $set . '_f104',
  'tooth-1 (dentistry set)' => $set . '_f105',
  'drilling (dentistry set)' => $set . '_f106',
  'dental-veneer (dentistry set)' => $set . '_f107',
  'dentist-chair (dentistry set)' => $set . '_f108',
  'mouthwash (dentistry set)' => $set . '_f109',
  'open-mouth (dentistry set)' => $set . '_f10a',
  'dentist (dentistry set)' => $set . '_f10b',
  'tooth-2 (dentistry set)' => $set . '_f10c',
  'tooth-3 (dentistry set)' => $set . '_f10d',
  'braces (dentistry set)' => $set . '_f10e',
  'braces-1 (dentistry set)' => $set . '_f10f',
  'tooth-4 (dentistry set)' => $set . '_f110',
  'removal (dentistry set)' => $set . '_f111',
  'crown (dentistry set)' => $set . '_f112',
  'tooth-5 (dentistry set)' => $set . '_f113',
  'tooth-6 (dentistry set)' => $set . '_f114',
  'floss (dentistry set)' => $set . '_f115',
  'tools (dentistry set)' => $set . '_f116',
  'toothbrush (dentistry set)' => $set . '_f117',
  'tooth-drill (dentistry set)' => $set . '_f118',
  'dentist-1 (dentistry set)' => $set . '_f119',
  'magnifying-glass (dentistry set)' => $set . '_f11a',
  'dentist-chair-1 (dentistry set)' => $set . '_f11b',
  'health-report (dentistry set)' => $set . '_f11c',
  'dentures (dentistry set)' => $set . '_f11d',
  'crown-1 (dentistry set)' => $set . '_f11e',
  'plaque (dentistry set)' => $set . '_f11f',
  'tooth-extraction (dentistry set)' => $set . '_f120',
  'x-ray (dentistry set)' => $set . '_f121',
  'forceps (dentistry set)' => $set . '_f122',
  'teeth-brushing (dentistry set)' => $set . '_f123',
  'toothbrush-1 (dentistry set)' => $set . '_f124',
  'toothbrush-2 (dentistry set)' => $set . '_f125',
  'calcium (dentistry set)' => $set . '_f126',
  'tooth-7 (dentistry set)' => $set . '_f127',
  'tooth-8 (dentistry set)' => $set . '_f128',
  'tooth-9 (dentistry set)' => $set . '_f129',
  'tooth-10 (dentistry set)' => $set . '_f12a',
  'tooth-11 (dentistry set)' => $set . '_f12b',
  'smartphone (dentistry set)' => $set . '_f12c',
  'tooth-12 (dentistry set)' => $set . '_f12d',
  'braces-2 (dentistry set)' => $set . '_f12e',
  'suction (dentistry set)' => $set . '_f12f',
  'tooth-fairy (dentistry set)' => $set . '_f130',
  'floss-1 (dentistry set)' => $set . '_f131'
);