<?php

$set = strtolower( basename(__FILE__, '.php') );

$$set = array(

	'bandage (health set)' => $set . '_f100',
	'cancer (health set)' => $set . '_f101',
	'pregnancy (health set)' => $set . '_f102',
	'medical-checkup (health set)' => $set . '_f103',
	'medical-app (health set)' => $set . '_f104',
	'prostate (health set)' => $set . '_f105',
	'prescription (health set)' => $set . '_f106',
	'examination (health set)' => $set . '_f107',
	'calendar (health set)' => $set . '_f108',
	'eye-examination (health set)' => $set . '_f109',
	'stress-test (health set)' => $set . '_f10a',
	'urine-test (health set)' => $set . '_f10b',
	'x-rays (health set)' => $set . '_f10c',
	'cotton-swab (health set)' => $set . '_f10d',
	'spine (health set)' => $set . '_f10e',
	'blood-test (health set)' => $set . '_f10f',
	'scale (health set)' => $set . '_f110',
	'height (health set)' => $set . '_f111',
	'hospital (health set)' => $set . '_f112',
	'dna (health set)' => $set . '_f113',
	'blood-bag (health set)' => $set . '_f114',
	'blood-pressure-gauge (health set)' => $set . '_f115',
	'ct-scan (health set)' => $set . '_f116',
	'reflex-hammer (health set)' => $set . '_f117',
	'mammogram (health set)' => $set . '_f118',
	'ultrasonography (health set)' => $set . '_f119',
	'cholesterol (health set)' => $set . '_f11a',
	'heart-rate (health set)' => $set . '_f11b',
	'ear (health set)' => $set . '_f11c',
	'microscope (health set)' => $set . '_f11d',
	'defribillator (health set)' => $set . '_f11e',
	'electrocardiogram (health set)' => $set . '_f11f',
	'bone (health set)' => $set . '_f120',
	'carcinoembryonic (health set)' => $set . '_f121',
	'stomach (health set)' => $set . '_f122',
	'thermometer (health set)' => $set . '_f123',
	'blood-urea-nitrogen (health set)' => $set . '_f124',
	'lungs (health set)' => $set . '_f125',
	'dental-checkup (health set)' => $set . '_f126',
	'hepatitis (health set)' => $set . '_f127',
	'doctor (health set)' => $set . '_f128',
	'phonendoscope (health set)' => $set . '_f129',
	'red-blood-cells (health set)' => $set . '_f12a',
	'mental-health (health set)' => $set . '_f12b',
	'pap-smear (health set)' => $set . '_f12c',
	'syringe (health set)' => $set . '_f12d',
	'glucose-meter (health set)' => $set . '_f12e',
	'medical-report (health set)' => $set . '_f12f',
	'diagnosis (health set)' => $set . '_f130',
	'thyroid (health set)' => $set . '_f131'
);