<?php

$set = strtolower( basename(__FILE__, '.php') );

$$set = array(

	'doctor (medic set)' => $set . '_e900',
	'stethoscopes_01 (medic set)' => $set . '_e901',
	'doctor_02 (medic set)' => $set . '_e902',
	'calendar (medic set)' => $set . '_e903',
	'doctor_03 (medic set)' => $set . '_e904',
	'clinic_01 (medic set)' => $set . '_e905',
	'heart_01 (medic set)' => $set . '_e906',
	'appointment_02 (medic set)' => $set . '_e907',
	'heart_02 (medic set)' => $set . '_e908',
	'heart_03 (medic set)' => $set . '_e909',
	'heart_04 (medic set)' => $set . '_e90a',
	'heart_05 (medic set)' => $set . '_e90b',
	'heart_06 (medic set)' => $set . '_e90c',
	'stethoscopes_02 (medic set)' => $set . '_e90d',
	'care (medic set)' => $set . '_e90e',
	'body_01 (medic set)' => $set . '_e90f',
	'body_02 (medic set)' => $set . '_e910',
	'body_03 (medic set)' => $set . '_e911',
	'leg (medic set)' => $set . '_e912',
	'world (medic set)' => $set . '_e913',
	'tube_test (medic set)' => $set . '_e914',
	'virus_01 (medic set)' => $set . '_e915',
	'diaphragm (medic set)' => $set . '_e916',
	'virus_02 (medic set)' => $set . '_e917',
	'mask (medic set)' => $set . '_e918',
	'hand_wash (medic set)' => $set . '_e919',
	'desinsection (medic set)' => $set . '_e91a',
	'distance (medic set)' => $set . '_e91b',
	'clinic_02 (medic set)' => $set . '_e91c',
	'nose (medic set)' => $set . '_e91d',
	'test (medic set)' => $set . '_e91e',
	'hand_washing (medic set)' => $set . '_e91f',
	'lungs_01 (medic set)' => $set . '_e920',
	'heart_07 (medic set)' => $set . '_e921',
	'brain (medic set)' => $set . '_e922',
	'lungs_02 (medic set)' => $set . '_e923',
	'eye (medic set)' => $set . '_e924',
	'spleen (medic set)' => $set . '_e925',
	'kidney (medic set)' => $set . '_e926',
	'bones (medic set)' => $set . '_e927',
	'teeth (medic set)' => $set . '_e928',
	'hair (medic set)' => $set . '_e929',
	'organ (medic set)' => $set . '_e92a',
	'colon (medic set)' => $set . '_e92b',
	'genitals (medic set)' => $set . '_e92c'
);
